project_id = "mowupnhjeghhbafjacza"

[functions.get-token-prices]
verify_jwt = false

[functions.increment-view]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.scan-pdf-security]
verify_jwt = true

[functions.watermark-epub]
verify_jwt = false

[functions.watermark-pdf]
verify_jwt = false